require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
prepare_react_native_project!

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => false,
    :fabric_enabled => false,
    :new_arch_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  post_install do |installer|
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end

      target.build_configurations.each do |config|
        # Общие настройки для всех таргетов
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC -lc++'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

        # Добавляем все библиотеки в пути поиска
        config.build_settings['LIBRARY_SEARCH_PATHS'] = [
          '$(inherited)',
          '$(PODS_ROOT)/DoubleConversion',
          '$(PODS_ROOT)/DoubleConversion/double-conversion',
          '$(PODS_ROOT)/RCT-Folly',
          '$(PODS_ROOT)/RCT-Folly/folly',
          '$(PODS_ROOT)/RCTDeprecation',
          '$(PODS_CONFIGURATION_BUILD_DIR)/DoubleConversion',
          '$(PODS_CONFIGURATION_BUILD_DIR)/RCT-Folly',
          '$(PODS_CONFIGURATION_BUILD_DIR)/RCTDeprecation'
        ]
      end
    end
  end
end
