name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        
      - uses: borales/actions-yarn@v3.0.0
        name: Validation
        with:
          cmd: install

      - name: Verify frozen assignment mapping
        run: yarn test src/internal/__tests__/Mapper.test.ts --runInBand
